# Generated by Django 4.1.5 on 2023-03-03 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_alter_evaluation_end_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_exporting', models.IntegerField(default=0)),
                ('plans_to_export', models.BooleanField(default=0)),
                ('export_variation', models.IntegerField(default=0)),
                ('foreign_investment', models.BooleanField(default=0)),
                ('average_years', models.IntegerField(default=0)),
                ('top_or_midle', models.IntegerField(default=0)),
                ('women_employed', models.IntegerField(default=0)),
                ('women_top_or_midle', models.IntegerField(default=0)),
                ('ceo_title', models.CharField(max_length=20)),
                ('given_name', models.CharField(max_length=100)),
                ('family_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('bussines_position', models.CharField(max_length=100)),
                ('years_in_the_post', models.IntegerField(default=0)),
                ('comments', models.TextField(max_length=255)),
                ('id_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('form_number', models.IntegerField(default=0)),
                ('id_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='MainProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30)),
                ('percentage', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('id_evaluation', models.ManyToManyField(to='evaluations.datamodel')),
            ],
        ),
    ]
