# Generated by Django 4.1.5 on 2023-03-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_datamodel_processscore_mainproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='plans_to_export',
            field=models.SmallIntegerField(default=0),
        ),
    ]
