# Generated by Django 4.1.5 on 2023-03-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_alter_datamodel_bussines_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datamodel',
            old_name='top_or_midle',
            new_name='top_or_middle',
        ),
        migrations.RenameField(
            model_name='datamodel',
            old_name='women_top_or_midle',
            new_name='women_top_or_middle',
        ),
    ]
