# Generated by Django 4.1.5 on 2023-03-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0009_alter_mainproducts_id_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproducts',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
