# Generated by Django 4.1.5 on 2023-03-14 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0005_additionalinformation_assess_five_and_more'),
        ('evaluations', '0010_alter_mainproducts_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='processscore',
            name='element',
            field=models.ForeignKey(default=165, on_delete=django.db.models.deletion.CASCADE, to='elements.element'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processscore',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
