# Generated by Django 4.1.5 on 2023-03-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0005_additionalinformation_assess_five_and_more'),
        ('evaluations', '0011_processscore_element_processscore_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='processscore',
            name='score_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='EvaluationRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='CompetenceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.IntegerField(default=0)),
                ('order', models.SmallIntegerField(default=0)),
                ('score_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('score_final', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.element')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='CapabilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.IntegerField(default=0)),
                ('order', models.SmallIntegerField(default=0)),
                ('score_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('score_final', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.element')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluation')),
            ],
        ),
    ]
