# Generated by Django 4.1.5 on 2023-03-17 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relations_tree', '0008_relationcap_parent_element_and_more'),
        ('evaluations', '0012_processscore_score_percentage_evaluationrating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processscore',
            name='relation_pro',
            field=models.ForeignKey(default=48, on_delete=django.db.models.deletion.CASCADE, to='relations_tree.relationpro'),
            preserve_default=False,
        ),
    ]
