# Generated by Django 4.1.5 on 2023-03-17 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relations_tree', '0008_relationcap_parent_element_and_more'),
        ('evaluations', '0013_processscore_relation_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='capabilityscore',
            name='relation_cap',
            field=models.ForeignKey(default=20031, on_delete=django.db.models.deletion.CASCADE, to='relations_tree.relationcap'),
            preserve_default=False,
        ),
    ]
