# Generated by Django 4.1.5 on 2023-03-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0014_capabilityscore_relation_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='processscore',
            name='score_transform',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
