# Generated by Django 4.1.5 on 2023-03-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0015_processscore_score_transform'),
    ]

    operations = [
        migrations.AddField(
            model_name='capabilityscore',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
