# Generated by Django 4.1.5 on 2023-03-18 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0016_capabilityscore_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvaluationRating',
        ),
    ]
