# Generated by Django 4.1.5 on 2023-03-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0017_delete_evaluationrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencescore',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='capabilityscore',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
