# Generated by Django 4.1.5 on 2023-04-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Country'),
        ),
    ]
