# Generated by Django 4.1.5 on 2023-02-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('year_establishment', models.IntegerField(default=1900)),
                ('year_first_expo', models.IntegerField(default=1900)),
                ('bussines_description', models.TextField(max_length=1000)),
                ('subsector', models.IntegerField(default=0)),
                ('sector', models.IntegerField(default=0)),
                ('supersector', models.IntegerField(default=0)),
                ('industry', models.IntegerField(default=0)),
                ('comments', models.CharField(max_length=250)),
                ('eva_made', models.IntegerField(default=0)),
                ('eva_progress', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
