# Generated by Django 4.1.5 on 2023-03-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_industry_remove_company_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='company',
            name='bussines_description',
            field=models.TextField(default='None', max_length=1000),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='comments',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='year_establishment',
            field=models.IntegerField(default=1950),
        ),
        migrations.AlterField(
            model_name='company',
            name='year_first_expo',
            field=models.IntegerField(default=1950),
        ),
    ]
