# Generated by Django 4.1.5 on 2023-03-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='bussines_description',
            field=models.TextField(blank=True, default='None', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='comments',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, default='None', max_length=20, null=True),
        ),
    ]
