# Generated by Django 4.1.5 on 2023-02-14 13:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Relation name')),
                ('total_elements', models.SmallIntegerField(default=0)),
                ('total_competences', models.SmallIntegerField(default=0)),
                ('total_capabilities', models.SmallIntegerField(default=0)),
                ('total_processes', models.SmallIntegerField(default=0)),
                ('eva_made', models.SmallIntegerField(default=0)),
                ('eva_progress', models.SmallIntegerField(default=0)),
                ('comments', models.CharField(max_length=255, verbose_name='Comments')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelationPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_number', models.SmallIntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('id_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relations_tree.relation')),
            ],
        ),
        migrations.CreateModel(
            name='RelationComp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_letter', models.CharField(max_length=2, verbose_name='Original letter')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('id_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relations_tree.relation')),
                ('relation_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.letter')),
            ],
        ),
        migrations.CreateModel(
            name='RelationCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_number', models.SmallIntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('id_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relations_tree.relation')),
            ],
        ),
    ]
