# Generated by Django 4.1.5 on 2023-02-19 20:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_remove_element_add_info_and_more'),
        ('general', '0001_initial'),
        ('relations_tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='relationcap',
            name='id_element',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='elements.element'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationcap',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='relationcomp',
            name='id_element',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='elements.element'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationcomp',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='relationpro',
            name='id_element',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='elements.element'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationpro',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='relation',
            name='comments',
            field=models.CharField(default='None', max_length=255, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='name',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinValueValidator(3)], verbose_name='Relation name'),
        ),
        migrations.AlterField(
            model_name='relationcomp',
            name='relation_letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.letter', verbose_name='Relation letter'),
        ),
    ]
