# Generated by Django 4.1.5 on 2023-02-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations_tree', '0003_alter_relationcomp_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationcap',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='relationpro',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
