# Generated by Django 4.1.5 on 2023-02-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relations_tree', '0004_alter_relationcap_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationcap',
            old_name='cap_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='relationpro',
            old_name='pro_number',
            new_name='number',
        ),
    ]
