# Generated by Django 4.1.5 on 2023-02-24 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('relations_tree', '0006_alter_relationcap_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationcap',
            name='relation_letter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='general.letter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationpro',
            name='relation_letter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='general.letter'),
            preserve_default=False,
        ),
    ]
