# Generated by Django 4.1.5 on 2023-03-16 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0005_additionalinformation_assess_five_and_more'),
        ('relations_tree', '0007_relationcap_relation_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationcap',
            name='parent_element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parent_element_cap', to='elements.element'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationpro',
            name='parent_element',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='parent_element_pro', to='elements.element'),
            preserve_default=False,
        ),
    ]
