# Generated by Django 4.1.5 on 2023-03-27 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('relations_tree', '0008_relationcap_parent_element_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationcomp',
            name='relation_letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter', to='general.letter', verbose_name='Relation letter'),
        ),
    ]
