# Generated by Django 4.1.5 on 2023-02-06 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15, verbose_name='Element Type')),
                ('name', models.CharField(max_length=250, verbose_name='Competence name')),
                ('comments', models.CharField(default='None', max_length=255, verbose_name='Comments')),
                ('eva_progress', models.IntegerField(default=0)),
                ('eva_made', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.letter')),
            ],
            options={
                'ordering': ('letter', 'name', 'created'),
            },
        ),
    ]
