# Generated by Django 4.1.5 on 2023-02-07 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definitions', models.TextField(verbose_name='Definitions')),
                ('symptoms', models.TextField(verbose_name='Symptoms')),
                ('questions', models.TextField(verbose_name='Sample questions')),
                ('id_element', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elements.element')),
            ],
        ),
    ]
