# Generated by Django 4.1.5 on 2023-02-08 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_additionalinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalinformation',
            name='id_element',
        ),
        migrations.AddField(
            model_name='element',
            name='add_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elements.additionalinformation'),
        ),
    ]
