# Generated by Django 4.1.5 on 2023-02-08 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_remove_additionalinformation_id_element_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='add_info',
        ),
        migrations.AddField(
            model_name='additionalinformation',
            name='add_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elements.element'),
        ),
    ]
