# Generated by Django 4.1.5 on 2023-03-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_remove_element_add_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinformation',
            name='assess_five',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='additionalinformation',
            name='assess_four',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='additionalinformation',
            name='assess_one',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='additionalinformation',
            name='assess_three',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='additionalinformation',
            name='assess_two',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='additionalinformation',
            name='definitions',
            field=models.TextField(default='None', verbose_name='Definitions'),
        ),
        migrations.AlterField(
            model_name='additionalinformation',
            name='questions',
            field=models.TextField(default='None', verbose_name='Sample questions'),
        ),
        migrations.AlterField(
            model_name='additionalinformation',
            name='symptoms',
            field=models.TextField(default='None', verbose_name='Symptoms'),
        ),
    ]
