# Generated by Django 4.1.5 on 2023-04-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elements", "0005_additionalinformation_assess_five_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="assess_five",
            field=models.TextField(default="None", max_length=1000),
        ),
        migrations.AddField(
            model_name="element",
            name="assess_four",
            field=models.TextField(default="None", max_length=1000),
        ),
        migrations.AddField(
            model_name="element",
            name="assess_one",
            field=models.TextField(default="None", max_length=1000),
        ),
        migrations.AddField(
            model_name="element",
            name="assess_three",
            field=models.TextField(default="None", max_length=1000),
        ),
        migrations.AddField(
            model_name="element",
            name="assess_two",
            field=models.TextField(default="None", max_length=1000),
        ),
        migrations.AddField(
            model_name="element",
            name="definitions",
            field=models.TextField(
                default="None", max_length=2000, verbose_name="Definitions"
            ),
        ),
        migrations.AddField(
            model_name="element",
            name="questions",
            field=models.TextField(
                default="None", max_length=3000, verbose_name="Sample questions"
            ),
        ),
        migrations.AddField(
            model_name="element",
            name="symptoms",
            field=models.TextField(
                default="None", max_length=3000, verbose_name="Symptoms"
            ),
        ),
        migrations.AlterField(
            model_name="additionalinformation",
            name="assess_five",
            field=models.TextField(default="None", max_length=1000),
        ),
        migrations.AlterField(
            model_name="additionalinformation",
            name="assess_four",
            field=models.TextField(default="None", max_length=1000),
        ),
        migrations.AlterField(
            model_name="additionalinformation",
            name="assess_one",
            field=models.TextField(default="None", max_length=1000),
        ),
        migrations.AlterField(
            model_name="additionalinformation",
            name="assess_three",
            field=models.TextField(default="None", max_length=1000),
        ),
        migrations.AlterField(
            model_name="additionalinformation",
            name="assess_two",
            field=models.TextField(default="None", max_length=1000),
        ),
        migrations.AlterField(
            model_name="additionalinformation",
            name="definitions",
            field=models.TextField(
                default="None", max_length=2000, verbose_name="Definitions"
            ),
        ),
        migrations.AlterField(
            model_name="additionalinformation",
            name="questions",
            field=models.TextField(
                default="None", max_length=3000, verbose_name="Sample questions"
            ),
        ),
        migrations.AlterField(
            model_name="additionalinformation",
            name="symptoms",
            field=models.TextField(
                default="None", max_length=3000, verbose_name="Symptoms"
            ),
        ),
    ]
