# Generated by Django 4.1.5 on 2023-04-08 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elements", "0006_element_assess_five_element_assess_four_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="element",
            old_name="type",
            new_name="element_type",
        ),
    ]
